export const AUTH_START = "AUTH_START";
export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CHECK_AUTH_TIMEOUT = "CHECK_AUTH_TIMEOUT";
export const AUTO_AUTH = "AUTO_AUTH";

export const SAVE_EMAIL_AND_CONTACT = "SAVE_EMAIL_AND_CONTACT";
export const SAVE_GENDER = "SAVE_GENDER";
export const SAVE_PASSWORD = "SAVE_PASSWORD";
export const SAVE_NAME = "SAVE_NAME";
export const SAVE_AGE = "SAVE_AGE";
export const SAVE_LOCATION = "SAVE_LOCATION";
export const SAVE_OCCUPATION = "SAVE_OCCUPATION";